video:
  width: 720
  height: 560
  fps_target: 20
  process_scale: 0.8        # 0.5..1.0 (downscales input before MediaPipe)

capture:
  window_ms: 450
  burst_frames: 11
  min_final_still_ms: 150

thresholds:
  # Core guards
  gesture_conf: 0.60
  min_landmarks: 15
  min_brightness: 40
  max_motion_last: 12.0

  # Extension detection
  ext_y_margin: 0.015              # tip must be at least this above PIP (Y)
  ext_score_margin: 0.06           # strong extension score (stricter)
  ext_score_loose_norm: 0.018      # slight extension score (used for relaxed rock)

  # Scissors
  min_scissor_gap_norm: 0.20       # normalized index↔middle tip gap for scissors
  scissor_fallback_gap_norm: 0.16  # fallback acceptance for near-scissors

  # Paper (strict)
  paper_min_extended: 4            # legacy (not used by v2 but ok to keep)
  paper_min_extended_loose: 3      # legacy (not used by v2 but ok to keep)
  paper_spread_min: 0.38           # legacy (not used by v2 but ok to keep)
  paper_spread_min_strict: 0.52    # index↔pinky min spread
  paper_min_adj_gap_norm: 0.20     # min gap for (idx-mid, mid-ring, ring-pinky)
  min_thumb_gap_for_paper_norm: 0.24

  # Rock (more forgiving but safe)
  max_thumb_gap_for_rock_norm: 0.33        # old strict guard
  max_thumb_gap_for_rock_loose_norm: 0.40  # allow slightly open thumb
  rock_max_avg_adj_gap_norm: 0.20          # average (idx-mid, mid-ring, ring-pinky)
  rock_max_index_pinky_spread_norm: 0.47   # overall spread cap for rock

ai:
  policy: "adaptive_freq"
  history: 40

mediapipe:
  model_complexity: 0      # 0=faster, 1=higher quality
  max_num_hands: 1
  detect_stride: 2         # overlay detection every N frames

fairness:
  lock_at_count: 2

logging:
  out_dir: "outputs"
  save_last_clip: false

ui:
  use_ttf_small: false
  effects:
    confetti_on_win: false
    shake_on_lose:  false
    countdown_ring: false
  visuals:
    gradient_backdrop: false
    vignette: false
    glass_panels: false
    glow_trail: false
    result_spotlight: false
